import {
  FileText,
  TrendingDown,
  MessageSquareWarning,
  AlertTriangle,
  Clock,
} from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";

interface Analysis {
  id: string;
  title: string;
  description: string;
  icon: typeof FileText;
  type: "Risk" | "Churn" | "Complaints";
  updated: string;
}

const analyses: Analysis[] = [
  {
    id: "a1",
    title: "At-Risk Accounts Overview",
    description: "High- and medium-risk customers with declining purchase volume over the last two quarters.",
    icon: AlertTriangle,
    type: "Risk",
    updated: "2h ago",
  },
  {
    id: "a2",
    title: "Churn Drivers",
    description: "Correlation between complaint volume and purchase reduction to surface churn signals.",
    icon: TrendingDown,
    type: "Churn",
    updated: "1d ago",
  },
  {
    id: "a3",
    title: "Complaint Themes",
    description: "Categorized complaint reasons aggregated across all accounts for the current period.",
    icon: MessageSquareWarning,
    type: "Complaints",
    updated: "3d ago",
  },
  {
    id: "a4",
    title: "Revenue Concentration",
    description: "Contribution of enterprise accounts to total revenue and exposure if any were to churn.",
    icon: FileText,
    type: "Risk",
    updated: "1w ago",
  },
];

const typeColor: Record<Analysis["type"], string> = {
  Risk: "text-red-600 dark:text-red-400",
  Churn: "text-amber-600 dark:text-amber-400",
  Complaints: "text-indigo-600 dark:text-indigo-400",
};

export function Analyses() {
  return (
    <div className="space-y-6">
      <div className="flex flex-col gap-1 pt-4">
        <h1 className="text-2xl font-semibold tracking-tight">Analyses</h1>
        <p className="text-sm text-muted-foreground">
          Saved insights generated by the Copilot from your customer data.
        </p>
      </div>

      <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
        {analyses.map((analysis, i) => {
          const Icon = analysis.icon;
          return (
            <Card
              key={analysis.id}
              className="animate-fade-in-up cursor-pointer transition-colors hover:border-primary/40"
              style={{ animationDelay: `${i * 60}ms` }}
            >
              <CardHeader className="flex flex-row items-start gap-4 space-y-0">
                <span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-primary">
                  <Icon className="h-5 w-5" />
                </span>
                <div className="space-y-1">
                  <CardTitle className="text-base leading-snug">{analysis.title}</CardTitle>
                  <CardDescription className="leading-relaxed">
                    {analysis.description}
                  </CardDescription>
                </div>
              </CardHeader>
              <CardContent className="flex items-center gap-2">
                <Badge variant="outline" className="gap-1.5">
                  <span className={`h-1.5 w-1.5 rounded-full ${typeColor[analysis.type]}`} />
                  {analysis.type}
                </Badge>
                <span className="inline-flex items-center gap-1 text-xs text-muted-foreground">
                  <Clock className="h-3 w-3" />
                  {analysis.updated}
                </span>
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}
